name: ZXYsPlugin
main: io.github.photozynthesis.zxysplugin.ZXYsPlugin
version: 0.1

commands:
 sheepgame:
  description: Sheeps have individual moods!
  aliases: sheep
  permission: zxy.sheepgame
  permission-message: "§cOnly ops can start or stop the SheepGame !"
  usage: "Use §a/sheepgame <start/stop>§r or §a/sheep <start/stop>§r !"
 chunktool:
  description: Util for tracing chunks!
  aliases: chunk
  permission: zxy.chunktool
  permission-message: "no permission !"
  usage: "[ChunkTool] Use §a/<chunktool/chunk> register <radius>§r to register current chunk.\n[ChunkTool] Use §a/<chunktool/chunk> show§r to show the loadmap.\n[ChunkTool] Warning: the max radius for chunks registration is §612§r !"
# usage: "[ChunkTool] Use §a/<chunktool/chunk> show§r to show the loadmap."
# usage: "[ChunkTool] Warning: the max radius for chunks registration is §612§r !"

permissions:
 zxy.sheepgame:
  default: op
 zxy.chunktool:
  default: true
 zxy.chunktool.unregisterall:
  default: op