name: ZXYsPlugin
main: io.github.photozynthesis.zxysplugin.ZXYsPlugin
version: 0.1

commands:
 sheepgame:
  description: Sheeps have individual moods!
  aliases: sheep
  permission: zxy.sheepgame
  permission-message: "§cOnly ops can start or stop the SheepGame !"
  usage: "Use §a/sheepgame <start/stop>§r or §a/sheep <start/stop>§r !"
 chunktool:
  description: Util for tracing chunks!
  aliases: chunk
  permission: zxy.chunktrace
  permission-message: "no permission !"
  usage: "Use §a/<chunktool/chunk> register <radius>§r to register current chunk. Use §a/<chunktool/chunk> show§r to show the loadmap."

permissions:
 zxy.sheepgame:
  default: op
 zxy.chunktrace:
  default: true