name: ZXYsPlugin
main: io.github.photozynthesis.zxysplugin.ZXYsPlugin
version: 1.1

commands:
 sheepgame:
  description: Sheeps have individual moods!
  aliases: sheep
  permission: zxy.sheepgame
  permission-message: "§cOnly ops can start or stop the SheepGame !"
  usage: "\n[SheepGame] 使用 §a/<sheepgame|sheep> <start|stop>§r 来让羊羊君爆炸 !\n[SheepGame] 启用后，可用§a右键§r调戏羊羊君!\n[SheepGame] 爆炸几率为 §c1/10§r ，爆炸前会进行提示。"
 chunktool:
  description: Util for tracing chunks!
  aliases: chunk
  permission: zxy.chunktool
  permission-message: "no permission !"
  usage: "\n[ChunkTool] 使用 §a/chunktool <register|reg> <radius...>§r 来注册区块。\n[ChunkTool] 使用 §a/chunktool show§r 来查看注册区块的加载情况。\n[ChunkTool] 使用 §a/chunktool <unregister|unreg>§r 来清除你的区块注册。\n[ChunkTool] §6OP: 使用 §a/chunktool showregs§6 来查看注册了区块的玩家。§f\n[ChunkTool] §6OP: 使用 §a/chunktool show <playername...>§6 来查看其他玩家注册区块的加载情况。§f\n[ChunkTool] §6OP: 使用 §a/chunktool <unregister|unreg> <playerName...>§6 来清除某个特定玩家的区块注册。§f\n[ChunkTool] §6OP: 使用 §a/chunktool <unregisterall|unregall>§6 来清除所有人的区块注册。§f\n[ChunkTool] §c警告: 目前最大的区块注册半径为 §a12§c !"
# usage: "[ChunkTool] Use §a/chunktool <register|reg> <radius...>§r to register current chunk."
# usage: "[ChunkTool] Use §a/chunktool show§r to show the loadmap."
# usage: "[ChunkTool] Use §a/chunktool <unregister|unreg>§r to unregister your registered chunks."
# usage: "[ChunkTool] §6OP: 使用 §a/chunktool showregs§6 来查看注册了区块的玩家。§f"
# usage: "[ChunkTool] §6OP: 使用 §a/chunktool show <playerName...>§6 来查看其他玩家注册区块的加载情况。§f"
# usage: "[ChunkTool] §6OP: 使用 §a/chunktool <unregister|unreg> <playerName...>§6 来清除某个特定玩家的区块注册。§f"
# usage: "[ChunkTool] §6OP: Use §a/chunktool <unregisterall|unregall>§6 to unregister registrations of all players.§f"
# usage: "[ChunkTool] §cWarning§r: the §6max radius§r for chunks registration is §612§r !"
 temperature:
  description: Show block infos related to local temperature.
  aliases: tem
  permission: zxy.temperature
  permission-message: "no permission !"
  usage: "[Temperature] 使用 §a/<temperature|tem>§r 来查看当前位置的温度和其他信息。"

permissions:
 zxy.sheepgame:
  default: op
 zxy.chunktool:
  default: true
 zxy.chunktool.op:
  default: op
 zxy.temperature:
  default: true