name: ZXYsPlugin
main: io.github.photozynthesis.zxysplugin.ZXYsPlugin
version: 1.0

commands:
 sheepgame:
  description: Sheeps have individual moods!
  aliases: sheep
  permission: zxy.sheepgame
  permission-message: "§cOnly ops can start or stop the SheepGame !"
  usage: "Use §a/sheepgame <start/stop>§r or §a/sheep <start/stop>§r !"
 chunktool:
  description: Util for tracing chunks!
  aliases: chunk
  permission: zxy.chunktool
  permission-message: "no permission !"
  usage: "[ChunkTool] Use §a/chunktool <register|reg> <radius...>§r to register current chunk.\n[ChunkTool] Use §a/chunktool show§r to show the loadmap.\n[ChunkTool] Use §a/chunktool <unregister|unreg>§r to unregister your registered chunks.\n[ChunkTool] §6OP§r: Use §a/chunktool <unregisterall|unregall>§r to unregister registrations of all players.\n[ChunkTool] §cWarning§r: the §6max radius§r for chunks registration is §612§r !"
# usage: "[ChunkTool] Use §a/chunktool <register|reg> <radius...>§r to register current chunk."
# usage: "[ChunkTool] Use §a/chunktool show§r to show the loadmap."
# usage: "[ChunkTool] Use §a/chunktool <unregister|unreg>§r to unregister your registered chunks."
# usage: "[ChunkTool] §6OP§r: Use §a/chunktool <unregisterall|unregall>§r to unregister registrations of all players."
# usage: "[ChunkTool] §cWarning§r: the §6max radius§r for chunks registration is §612§r !"

permissions:
 zxy.sheepgame:
  default: op
 zxy.chunktool:
  default: true
 zxy.chunktool.unregisterall:
  default: op